version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - contoso-network

  contosoapp:
    image: contosoappimage:latest
    container_name: contosoapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

    # environment:
    #   - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ContosoUniversity;User Id=sa;Password=YourStrong!Passw0rd;
    ports:
      - "5135:5134"
    depends_on:
      - sqlserver
    networks:
      - contoso-network

networks:
  contoso-network:
    driver: bridge
